server:
  port: 8080

spring:
  jackson:
    mapper:
spring.jackson.mapper.DEFAULT_VIEW_INCLUSION: true
spring.jackson.serialization.indent_output: true
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS: false
spring.jackson.deserialization.FAIL_ON_IGNORED_PROPERTIES: false
spring.jackson.deserialization.FAIL_ON_UNKNOWN_PROPERTIES: false
spring.jackson.deserialization.ACCEPT_SINGLE_VALUE_AS_ARRAY: true
spring.jackson.default-property-inclusion: non_empty


  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: user
    password: password
    cachePrepStmts: true
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048
    useServerPrepStmts: true

  jpa:
    openInView: true
    show_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      # fixes Caused by: java.sql.SQLFeatureNotSupportedException: Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented.
      hibernate.jdbc.lob.non_contextual_creation: true

  data:
    jpa:
      repositories.enabled: true

logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    com.example: DEBUG
  file: app.log
